name: youtube_downloader
description: Application to download any video in a easy way in any format.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  youtube_explode_dart: ^1.4.1+3
  async: ^2.4.2
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  hydrated_bloc: ^6.0.0
  equatable: ^1.2.3
  search_app_bar:
    path: ../search_app_bar
  debounce_throttle: ^1.1.0
  filesystem_picker:
    path: ../filesystem_picker
  path_provider: ^1.6.11
  permission_handler: ^5.0.1+1
  settings_ui: ^0.3.0
  open_file: ^3.0.1
  android_path_provider: ^0.1.1
  flutter_local_notifications: ^1.4.4+2


flutter:
  uses-material-design: true

